services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ConnectHolland\KvkApiBundle\:
        resource: './*'
        exclude: './{Tests}'

    ConnectHolland\KvkApiBundle\API\ClientFactory: ~

    ConnectHolland\KvkApiBundle\API\Client\Client:
        public: true
        factory: 'ConnectHolland\KvkApiBundle\API\ClientFactory:createApiClient'
        arguments:
            - '@ch_kvk_api.guzzle_client'
            - '%ch_kvk_api.api_key%'
            - '%ch_kvk_api.use_testing_account%'

    ch_kvk_api.guzzle_client:
        class: 'GuzzleHttp\Client'
        arguments:
            - {'base_uri': '%ch_kvk_api.uri%' }
        tags:
            - { name: 'csa_guzzle.client', middleware: 'logger' }
